#ifndef DAU_CORE_H
#define DAU_CORE_H

/* Generated with cbindgen:0.27.0 */

/* Generated by cbindgen from dau-core. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Maximum UTF-32 code points returned in a single [`DauResult`].
//
// Kept as a literal `64` in [`DauResult::chars`] so cbindgen emits a valid C array size.
#define DAU_RESULT_MAX_CHARS 64

// Suggested action for the host IME bridge after a key event.
typedef enum DauAction {
  DauAction_None = 0,
  DauAction_UpdatePreedit = 1,
  DauAction_Commit = 2,
  DauAction_Restore = 3,
} DauAction;

// Input method selection for the C ABI.
typedef enum DauMethod {
  DauMethod_Telex = 0,
  DauMethod_Vni = 1,
} DauMethod;

// Per-app typing strategy for the C ABI.
typedef enum DauStrategy {
  DauStrategy_Unknown = 0,
  DauStrategy_Preedit = 1,
  DauStrategy_CommitAtom = 2,
  DauStrategy_Passthrough = 3,
} DauStrategy;

// Core composing engine for one word at a time.
typedef struct Engine Engine;

// Result of one key / break / escape operation.
//
// C++ reads `chars[0..len]` as UTF-32 code points.
typedef struct DauResult {
  enum DauAction action;
  // UTF-32 code points (valid prefix length is `len`, max 64).
  uint32_t chars[64];
  uint32_t len;
  bool capitalize_next;
} DauResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Backspace one user-visible Unicode scalar while composing.
//
// Returns [`DauAction::UpdatePreedit`] with the new preedit text when a scalar
// was removed (including empty text after deleting the last scalar). Returns
// [`DauAction::None`] when the compose buffer is already empty (host may pass
// the physical Backspace through) or when the engine is null / disabled.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
struct DauResult dau_backspace(struct Engine *engine);

// Clear the composing word.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
void dau_clear(struct Engine *engine);

// Free an engine previously returned by [`dau_engine_new`].
//
// Null is a no-op.
//
// # Safety
// - `engine` must be null or a unique pointer previously returned by [`dau_engine_new`].
// - Must not be used after this call (except null).
void dau_engine_free(struct Engine *engine);

// Create a new engine. Caller must free with [`dau_engine_free`].
struct Engine *dau_engine_new(enum DauMethod method);

// ESC: restore raw keystrokes. Returns [`DauAction::Restore`].
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
struct DauResult dau_escape(struct Engine *engine);

// Load config from shipped then user TOML paths (UTF-8 C strings; null = skip that file).
//
// Merges (user overrides shipped), stores on the engine, and applies method / enabled /
// auto_* / shortcuts when declared. Returns `true` if both parses succeeded (or files
// were skipped / missing).
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
// - Non-null path pointers must be valid NUL-terminated UTF-8 C strings for this call.
bool dau_load_config(struct Engine *engine, const char *shipped_path, const char *user_path);

// End the current word with break character `brk` (UTF-32).
//
// Returns [`DauAction::Commit`] with committed text (break char not included).
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
struct DauResult dau_on_break(struct Engine *engine, uint32_t brk);

// Process one Unicode scalar value (`ch` is UTF-32).
//
// Returns [`DauAction::UpdatePreedit`] while composing, or [`DauAction::None`]
// when the engine is disabled / null / invalid code point.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
struct DauResult dau_process_char(struct Engine *engine, uint32_t ch, bool caps);

// Enable/disable auto-capitalize after sentence ends.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
void dau_set_auto_capitalize(struct Engine *engine, bool on);

// Enable/disable English auto-restore on word break.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
void dau_set_auto_restore(struct Engine *engine, bool on);

// Enable or disable composition (when disabled, process/break/escape are no-ops).
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
void dau_set_enabled(struct Engine *engine, bool enabled);

// Switch input method. Does not clear the current buffer.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
void dau_set_method(struct Engine *engine, enum DauMethod method);

// Load shortcut pairs from a flat C array of UTF-8 C strings.
//
// `pairs` points to `2 * count` pointers: (key0, value0, key1, value1, ...).
// Null entries are skipped. Replaces any previous shortcut table.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
// - If `pairs` is non-null, it must point to at least `2 * count` readable
//   `*const c_char` entries; each non-null entry must be a valid NUL-terminated
//   UTF-8 C string that remains valid for the duration of this call.
void dau_set_shortcuts(struct Engine *engine, const char *const *pairs, size_t count);

// Look up the typing strategy for `app_id` from the engine's loaded config.
//
// Returns [`DauStrategy::Unknown`] when the engine is null, `app_id` is null/invalid,
// or no strategy is configured for that app.
//
// # Safety
// - `engine` must be null or a valid live pointer from [`dau_engine_new`].
// - Non-null `app_id` must be a valid NUL-terminated UTF-8 C string for this call.
enum DauStrategy dau_strategy_for_app(struct Engine *engine, const char *app_id);

// Crate version as a static C string. Do **not** free.
const char *dau_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DAU_CORE_H */
